### ISSUE TITLE
Fix: console warning, error 해결 요청

### ISSUE THREAD

**Issue by dev-seomoon** [Pre-Onboarding-FE-Team07/wanted-codestates-project-7-6#13]
### Issue Type
ex) 기능 추가 / 기능 삭제 / 버그 수정 / 의존성, 환경 변수, 빌드 관련 코드 업데이트
버그 수정

### Summary
콘솔 warning, error 해결 요청

### Description
<img width="541" alt="스크린샷 2022-03-08 오전 4 37 55" src="https://user-images.githubusercontent.com/52448114/157110004-ed1541f1-5ca1-4b06-a992-bd8630c6706c.png">

- assets/arrow_icon.svg 파일에서 error 발생하고 있음
- css import 구문 사용과 관련된 warning : 웹폰트 관련 warning으로, 
  전역 css에서 `@import url(//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css);` 사용하는 대신  
  index.html에 `<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css' rel='stylesheet' type='text/css'>`추가해서 해결해주세요.

**Comment by Lee-ye-ji** [comment]
이슈를 늦게 봤습니다. 기능 만들면서 같이 해결하였으니 확인 부탁드릴게요!
